all: Answer.class Question.class Exam.class ExamDriver.class
Answer.class : Answer.java
	javac -g Answer.java

Question.class : Question.java
	javac -g Question.java

Exam.class : Exam.java
	javac -g Exam.java

ExamDriver.class : ExamDriver.java
	javac -g ExamDriver.java
clean:
	rm *.class
